# Use root/example as user/password credentials
# use root as user and passward to make conection and login to db
version: '3.1'
services:
  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: testDB
      MYSQL_DATABASE: myDB
      MYSQL_USER: test
    volumes:
      - $PWD/../mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8079:8080
